### ISSUE TITLE
Add API Key Expiry Time

### ISSUE THREAD

**Issue by ghost** [MominIqbal-1234/webraft#2]

**Comment by MominIqbal-1234** [comment]
Done
pip install webraft --upgrade

**Comment by MominIqbal-1234** [comment]
Done 
pip install webraft --upgrade

key = APIKey(api_secret_key='my_key', expiry_token=120,algorithm='HS256')
token1 = key.create({"username":"momin","userid":1})
readToken =key.read(token1)
